#pragma once

#include <QColor>
#include <QString>

// Tipos de trilho (kind). Strings p/ serialização estável no JSON.
namespace TimelineKind {
constexpr auto Main      = "main";       // linha principal do projeto
constexpr auto Backstory = "backstory";  // passado / pré-história
constexpr auto Character = "character";  // trilha de um personagem (auto)
constexpr auto Lore      = "lore";       // lore / mundo
constexpr auto Parallel  = "parallel";   // linha paralela
constexpr auto Custom    = "custom";     // criada à mão, sem semântica especial
}

// Importância visual da linha — controla espessura do trilho e tamanho das
// bolinhas. Independente do `kind` semântico. Strings p/ JSON estável.
namespace TimelineWeight {
constexpr auto Primary   = "primary";    // principal — trilho grosso, bolinha grande
constexpr auto Secondary = "secondary";  // secundária — padrão
constexpr auto Backstory = "backstory";  // backstory / flashback — trilho tracejado
}

// Espessura (px) do trilho-guia por importância.
inline qreal weightLineWidth(const QString& w) {
    if (w == QLatin1String(TimelineWeight::Primary))   return 4.0;
    if (w == QLatin1String(TimelineWeight::Backstory)) return 2.5;
    return 3.0; // secondary (padrão)
}
// Fator de escala do raio da bolinha por importância.
inline qreal weightDotScale(const QString& w) {
    if (w == QLatin1String(TimelineWeight::Primary))   return 1.5;
    if (w == QLatin1String(TimelineWeight::Backstory)) return 1.25;
    return 1.0; // secondary
}
// Backstory / flashback desenha o trilho tracejado (convenção de passado/memória).
inline bool weightIsDashed(const QString& w) {
    return w == QLatin1String(TimelineWeight::Backstory);
}

struct TimelineDef {
    QString id;
    QString name;
    QColor  color = QColor(QStringLiteral("#6c8ebf"));

    QString kind      = QStringLiteral("custom"); // ver TimelineKind
    QString weight    = QStringLiteral("secondary"); // ver TimelineWeight (importância visual)
    int     railOrder = 0;            // posição vertical da faixa (Modo Trilho)

    // Ramificação: este trilho "descola" de um ponto de outro (estilo branch de git)
    QString parentId;                 // trilho-pai (vazio = raiz)
    QString branchFromEventId;        // evento de ancoragem no pai

    // Tracking de personagem
    QString characterId;              // Element.id quando kind == Character
    bool    autoGenerated = false;    // gerado pelo detector de presença
};

struct TimelineEvent {
    QString id;
    QString timelineId;
    QString title;
    QString description;
    QColor  color;                    // inválida = herda da timeline

    // Posição temporal — dois eixos, alternáveis na UI
    qreal   narrativeTick = -1.0;     // ordem de leitura (cap/cena); -1 = indefinido
    qreal   storyOrder    = -1.0;     // tempo da história (ordenável); -1 = indefinido
    QString timeMarker;               // rótulo textual ("Dia 5", "05/07/XXXX")

    // Posição livre (Modo Constelação)
    qreal   x = 0;
    qreal   y = 0;

    // Vínculos
    QString linkedSceneId;
    QString linkedDocId;
    QString conclusion;               // resumo da cena (texto livre)

    bool    autoEvent = false;        // veio do detector de presença (ponto "macio")
};

// Tipos de conexão entre eventos (define cor/estilo do fio)
namespace TimelineConnType {
constexpr auto Sequence   = "sequence";   // mesma linha, ordem temporal
constexpr auto Causal     = "causal";     // um evento causa o outro
constexpr auto Copresence = "copresence"; // personagens juntos na cena
constexpr auto Reference  = "reference";  // alusão / eco de lore
constexpr auto Branch     = "branch";     // ramificação de trilho
}

struct TimelineConn {
    QString id;
    QString fromEventId;
    QString toEventId;
    QString type = QStringLiteral("sequence");
    // cor = mix RGB das timelines dos dois eventos — calculada na hora de desenhar
};
